t = -0.02:10^(-7):0.02;

mt = (1-abs(t/0.01+1)).*(t >= -0.02 & t <= 0) - (1-abs(t/0.01-1)).*(t >= 0 & t <= 0.02);

Ac = 1;
fc = 10^6;
ct = Ac*cos(2*pi*fc*t);

s_mm = multiplier_mod(mt, ct);
s_nlm = non_lin_mod(mt, ct);
s_sm = switch_mod(mt, ct);
figure;
subplot(2, 2, 1);
plot(t, mt);
title("Message signal");
xlabel("time");
ylabel("m(t)");
subplot(2, 2, 2);
plot(t, s_mm);
title("Multiplier-Modulated");
xlabel("time");
ylabel("s_mm(t)");
subplot(2, 2, 3);
plot(t, real(s_nlm));
title("Non-Linear-Modulated");
xlabel("time");
ylabel("s_nlm(t)");
subplot(2, 2, 4);
plot(t, real(s_sm));
title("Switching-Modulated");
xlabel("time");
ylabel("s_sm(t)");

mt_sdm = switch_demod(s_sm, ct, 100);
figure;
subplot(1, 2, 1);
plot(t, mt);
title("Message Signal");
xlabel("time");
ylabel("m(t)");
subplot(1, 2, 2);
plot(t, real(mt_sdm));
title("Demodulated Signal");
xlabel("time");
ylabel("mt_{dm}(t)");

s_1 = mt.*cos(2*pi*fc*t + pi/3);
s_2 = mt.*cos(2*pi*(fc-5)*t);
s_3 = mt.*cos(2*pi*(fc-5)*t + pi/3);
mt_1 = 2*lowpass(s_1.*cos(2*pi*fc*t), 100, 1/Ts);
mt_2 = 2*lowpass(s_2.*cos(2*pi*fc*t), 100, 1/Ts);
mt_3 = 2*lowpass(s_3.*cos(2*pi*fc*t), 100, 1/Ts);

figure;
plot(t, mt_3);
hold on;
plot(t, mt_2);
hold on;
plot(t, mt_1);

figure;
subplot(3, 1, 1);
plot(-length(abs(fft(mt)))/2+1/2:length(abs(fft(mt)))/2-0.5, fftshift(abs(fft(mt))));
title("Freq Spectrum of m(t)");
xlabel("k");
ylabel("M(k)");
subplot(3, 1, 2);
plot(-length(abs(fft(s_1)))/2+0.5:length(abs(fft(s_1)))/2-0.5, fftshift(abs(fft(s_1))));
title("Freq Spectrum of mod (switch) signal");
xlabel("k");
ylabel("\phi_{DSB-SC}(k)");
subplot(3, 1, 3);
plot(-length(abs(fft(mt_1)))/2+0.5:length(abs(fft(mt_1)))/2-0.5, fftshift(abs(fft(mt_1))));
title("Freq Spectrum of demod signal with \deltaf=0 and \delta\theta=\pi/3");
xlabel("k");
ylabel("M_1(k)");

figure;
subplot(3, 1, 1);
plot(-length(abs(fft(mt)))/2+1/2:length(abs(fft(mt)))/2-0.5, fftshift(abs(fft(mt))));
title("Freq Spectrum of m(t)");
xlabel("k");
ylabel("M(k)");
subplot(3, 1, 2);
plot(-length(abs(fft(s_2)))/2+0.5:length(abs(fft(s_2)))/2-0.5, fftshift(abs(fft(s_2))));
title("Freq Spectrum of mod (switch) signal");
xlabel("k");
ylabel("\phi_{DSB-SC}(k)");
subplot(3, 1, 3);
plot(-length(abs(fft(mt_2)))/2+0.5:length(abs(fft(mt_2)))/2-0.5, fftshift(abs(fft(mt_2))));
title("Freq Spectrum of demod signal with \deltaf=5 and \delta\theta=0");
xlabel("k");
ylabel("M_2(k)");

figure;
subplot(3, 1, 1);
plot(-length(abs(fft(mt)))/2+1/2:length(abs(fft(mt)))/2-0.5, fftshift(abs(fft(mt))));
title("Freq Spectrum of m(t)");
xlabel("k");
ylabel("M(k)");
subplot(3, 1, 2);
plot(-length(abs(fft(s_3)))/2+0.5:length(abs(fft(s_3)))/2-0.5, fftshift(abs(fft(s_3))));
title("Freq Spectrum of mod (switch) signal");
xlabel("k");
ylabel("\phi_{DSB-SC}(k)");
subplot(3, 1, 3);
plot(-length(abs(fft(mt_3)))/2+0.5:length(abs(fft(mt_3)))/2-0.5, fftshift(abs(fft(mt_3))));
title("Freq Spectrum of demod signal with \deltaf=5 and \delta\theta=\pi/3");
xlabel("k");
ylabel("M_3(k)");